export const workObj = [
  {
    title: "My Blind Spots",
    thumbnail: "my-blind-spots.png",
    id: "myBlindSpots",
    desc: "Web development for a client's business that caters for the mentally challenged.",
    snapshot: ["myblindspots-screen.png"],
  },
  {
    title: "Boxti",
    thumbnail: "boxtilogo.png",
    id: "boxti",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod molestias eius ipsam vitae possimus iusto.",
    snapshot: ["boxti-home.png", "boxti-corporate.png", "boxti-about.png"],
  },
  {
    title: "Annie Pirotta",
    thumbnail: "annie-pirotta.png",
    id: "annieP",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod molestias eius ipsam vitae possimus iusto.",
    snapshot: ["anniepirotta-home.png", "anniepirotta-sym.png"],
  },
  {
    title: "Kader Boot Co.",
    thumbnail: "kader-boot-co.png",
    id: "KBC",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod molestias eius ipsam vitae possimus iusto.",
    snapshot: ["kader-home.png", "kader-shop.png", "kader-about.png"],
  },
  {
    title: "All West Engineering",
    thumbnail: "all-west-eng.png",
    id: "allWest",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod molestias eius ipsam vitae possimus iusto.",
    snapshot: [
      "lms-1.png",
      "lms-2.png",
      "lms-3.png",
      "lms-4.png",
      "lms-5.png",
      "lms-6.png",
    ],
  },
  {
    title: "Perfect Cotton",
    thumbnail: "perfectcottonlogo.png",
    id: "perfectCotton",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod molestias eius ipsam vitae possimus iusto.",
    snapshot: ["perfectcotton-home.png", "perfectcotton-shop.png"],
  },
  {
    title: "Print Strategy Management",
    thumbnail: "psmlogo.png",
    id: "PSM",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod molestias eius ipsam vitae possimus iusto.",
    snapshot: ["psm-home.png", "psm-products.png", "psm-about.png"],
  },
];
